# Generated by Django 3.2.5 on 2021-07-17 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_commentbox_addcommentbutton'),
        ('forum', '0008_rename_post_id_comment_post'),
    ]

    operations = [
    ]
