# Generated by Django 3.2.5 on 2021-07-17 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(default='no_image.png', upload_to='images/community')),
                ('founder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='community_members', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(related_name='community_posts', to='forum.Post')),
            ],
        ),
    ]
