# Generated by Django 4.0.dev20210716184641 on 2021-07-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_community_communitydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydetail',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communitydetail',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='communitydetail',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
