# Generated by Django 4.0.dev20210716184641 on 2021-07-17 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('community', '0004_communitydetail_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydetail',
            name='founder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
