# Generated by Django 4.0.dev20210716184641 on 2021-07-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Community',
            new_name='CommunityDetail',
        ),
    ]
