# Generated by Django 3.2.5 on 2021-07-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_addcommentbutton_commentbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentbox',
            name='post_id',
        ),
        migrations.DeleteModel(
            name='AddCommentButton',
        ),
        migrations.DeleteModel(
            name='CommentBox',
        ),
    ]
